# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [ ]:
import numpy as np

def array_factory(mode, shape, value=None):

    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    # TODO: Students implement logic here
    pass

In [1]:
import numpy as np
def array_factory():
    mode = input('Insert the mode you want (zeros, ones, full, identity): ')
    if mode=='zeros':
        rows = int(input('Enter number of rows: '))
        cols = int(input('Enter number of columns: '))
        return np.zeros((rows, cols))
    elif mode=='ones':
        rows = int(input('Enter number of rows: '))
        cols = int(input('Enter number of columns: '))
        return np.ones((rows, cols))
    elif mode=='full':
        rows = int(input('Enter number of rows: '))
        cols = int(input('Enter number of columns: '))
        value = float(input('Enter the value to fill: '))
        return np.full((rows, cols), value)
    elif mode=='identity':
        shape = int(input('Enter the size of the identity matrix: '))
        return np.eye(shape)
    else:
        return 'value erorr invalid mode'    
array_factory()

array([[0., 0., 0.],
       [0., 0., 0.]])

Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [ ]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        # Convert inputs to ndarray to ensure they are processed as Tensors 
        # arr = np.array(data1)

        arr1 = # TODO
        arr2 = # TODO

        # Rule: Change the shape of arr1 to new_shape 
        # Common usage: turning a vector (1D) into a matrix (2D)  by using reshape function 
        reshaped_arr1 = # TODO

        # Rule: Vertical Stacking (vstack) 
        # Requirement: Both matrices must have the same number of columns
        combined_dataset = # TODO

        return # TODO

    except ValueError as e:
        # Handle cases where reshape size doesn't match or stack columns don't match
        raise ValueError(f"Company-grade Error: {e}")

In [2]:
import numpy as np

def secure_reshape_and_stack():
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)
        reshaped_arr1 = arr1.reshape(new_shape)
        if arr2.ndim == 1:
            arr2 = arr2.reshape(1, -1)
        if reshaped_arr1.shape[1] != arr2.shape[1]:
            raise ValueError("Number of columns do not match for vertical stacking.")
        combined_dataset = np.vstack([reshaped_arr1, arr2])
        return combined_dataset
    except ValueError as e:
        print(f"⚠ Company-grade Error: {e}")
        return None
data1=[1,2,3,4]
data2=[[5,6],[7,9]]
new_shape=(2,2)
secure_reshape_and_stack()

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 9]])

part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [ ]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold) 
    and replaces them with a new value.
    """
    # 1. Convert input to a numpy array (ndarray)
    arr = # TODO
    # 2. Define the condition: elementwise comparison 
    # This creates a Boolean numpy array 
    condition = # TODO
    
    # 3. Apply Modification using np.where() 
    # np.where(condition, value_if_true, value_if_false)
    modified_arr = #TODO
    
    return modified_arr

In [3]:
import numpy as np
def prepare_and_apply_threshold(data1, data2, new_shape, threshold, replacement_value=-1):
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)
        reshaped_arr1 = arr1.reshape(new_shape)
        if arr2.size == 0:
            combined = reshaped_arr1
        else:
            if arr2.ndim == 1:
                arr2 = arr2.reshape(1, -1)
            if reshaped_arr1.shape[1] != arr2.shape[1]:
                raise ValueError("Number of columns do not match for vertical stacking.")
            combined = np.vstack([reshaped_arr1, arr2])
        modified = np.where(combined >= threshold, replacement_value, combined)
        print("Final Report:")
        print(modified)
        return modified
    except ValueError as e:
        print(f"⚠ Company-grade Error: {e}")
        return None


TestCase

In [ ]:
# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6] 

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = [[7, 8, 9], 
            [10, 11, 12]]

# Reshape A to 2x3 and stack with B
final_report = apply_threshold(branch_a, branch_b, (2, 3))
print(final_report)
# Resulting shape: (4, 3)

NameError: name 'apply_threshold' is not defined

In [4]:
branch_a = [1, 2, 3, 4, 5, 6]
branch_b = [[7, 8, 9],
            [10, 11, 12]]
final_report = prepare_and_apply_threshold(branch_a, branch_b, (2,3), threshold=7, replacement_value=-1)

Final Report:
[[ 1  2  3]
 [ 4  5  6]
 [-1 -1 -1]
 [-1 -1 -1]]


In [5]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


NameError: name 'apply_threshold' is not defined

In [102]:
v = np.array([1, 2, 3])
prepare_and_apply_threshold(v, [], (1,3), threshold=2, replacement_value=-20)

Final Report:
[[  1 -20 -20]]


array([[  1, -20, -20]])